### ISSUE TITLE
Neither architype, nor library exist in Maven

### ISSUE THREAD

**Issue by blublinsky** [ververica/stateful-functions#21]
Documentation https://statefun.io/getting_started/project_setup.html
Refers to archtype
$ mvn archetype:generate                    \
  -DarchetypeGroupId=com.ververica \
  -DarchetypeArtifactId=stateful-functions-quickstart \
  -DarchetypeVersion=1.1-SNAPSHOT

And dependency
<dependency>
    <groupId>com.ververica</groupId>
    <artifactId>stateful-functions-sdk</artifactId>
    <version>1.1-SNAPSHOT</version>
</dependency>

Neither one of which exists in mvn

**Comment by igalshilman** [comment]
Hello @blublinsky,

Currently the way to use the archetype is by first building the project locally (you can follow the instructions [here](https://github.com/ververica/stateful-functions#building-the-project) 

We haven't published the artifacts to maven central, because the project is on its way to be a part of Apache Flink, and it would be published to maven central under its new artifact and package names (we will update the documentation once it happens)

**Comment by blublinsky** [comment]
Thanks Igal,
What is the timeframe for moving this to Flink?

**Comment by igalshilman** [comment]
We are in the process of migrating the code to the new [repository](https://github.com/apache/flink-statefun) and this should be completed next week, but an actual release would happen and some time later this/next month. 

I'm wondering, for PoCing with Stateful Function at the moment, is it a big inconvenience for you to build the project yourself?

Thanks.

**Comment by blublinsky** [comment]
Thanks Igal,
Its fine for trying it out, was just wondering how real it is
