### ISSUE TITLE
Scala DSL

### ISSUE THREAD

**Issue by omidb** [ververica/stateful-functions#39]
Hi,

Any path for a Scala dsl? It can be a match made in heaven.

Thanks!

**Comment by igalshilman** [comment]
Hi @omidb 

Scala native DSL would be indeed a great match, however it is not on our immediate roadmap.

We were hopping that adding support for language X would be a community driven effort, since there are many different ways of implementing an API. (i.e. in Scala - monadic API or just a Java wrapper with implicits, or continuation based etc')

I'm wondering were there any parts of the API that you looked at and was thinking to yourself "oh in Scala that would have been so much nicer?"

Thanks a lot for your feedback,
Igal
